name: build package and container

on:
  push:
    tags:
      - "v*.*.*"

  pull_request:
    branches: [main, master]

jobs:
  build-container:
    uses: actions/workflows/.gitea/workflows/build_container.yml@master
    with:
      registry: docker.io
      image-name: olofvndrhr/manga-dlp
      context: .
      dockerfile: docker/Dockerfile
      platforms: linux/amd64,linux/arm64
    secrets:
      cr-username: ${{ secrets.CR_USERNAME }}
      cr-password: ${{ secrets.CR_PASSWORD }}

  build-pypackage:
    uses: actions/workflows/.gitea/workflows/release_pypackage.yml@master
    with:
      repository: main
    secrets:
      username: __token__
      token: ${{ secrets.PYPI_TOKEN }}
