name: check code

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  check-docs:
    runs-on: python3.12
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: "build docs"
        run: |
          python3 -m pip install mkdocs
          cd docs || exit 1
          mkdocs build --strict

  check-code:
    runs-on: python3.12
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: install hatch
        run: pip install -U hatch

      - name: test codestyle
        run: hatch run lint:style

      - name: test typing
        run: hatch run lint:typing

      - name: run tests
        if: github.event_name == 'pull_request'
        run: hatch run test:test

  scan-code:
    runs-on: python3.12
    if: github.event_name != 'pull_request'
    needs: ["check-code"]
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: install hatch
        run: pip install -U hatch

      # - name: get coverage (hatch)
      #   run: hatch run test:cov

      - name: run sonar-scanner
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
