name: create release

on:
  push:
    tags:
      - "v*.*.*"

  pull_request:
    branches: [main, master]

jobs:
  release-pypackage:
    runs-on: python3.12
    env:
      HATCH_INDEX_REPO: main
      HATCH_INDEX_USER: __token__
      HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'

      - name: install hatch
        run: pip install -U hatch hatchling

      - name: build package
        run: hatch build --clean

      - name: get release notes
        id: release-notes
        uses: olofvndrhr/releasenote-gen@v1

      - name: create gitea release
        uses: https://github.com/actions/release-action@main
        if: github.event_name != 'pull_request'
        with:
          title: ${{ github.ref_name }}
          body: ${{ steps.release-notes.outputs.releasenotes }}
          files: |-
            dist/**

      - name: create github release
        uses: ncipollo/release-action@v1
        if: github.event_name != 'pull_request'
        with:
          token: ${{ secrets.GH_TOKEN }}
          owner: olofvndrhr
          repo: manga-dlp
          name: ${{ github.ref_name }}
          body: ${{ steps.release-notes.outputs.releasenotes }}
          artifacts: |-
            dist/**
