name: run scheduled tests

on:
  schedule:
    - cron: "0 20 1 * *"

jobs:
  check-code-py311:
    runs-on: python3.12
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install hatch
        run: pip install -U hatch

      - name: run tests
        run: hatch run test:test
