version: "3"
services:

  manga-dlp:
    image: olofvndrhr/manga-dlp:2.1.5
    container_name: manga-dlp
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - appnet
    volumes:
      - ./downloads/:/app/downloads/ # default manga download directory
      - ./mangas.txt:/app/mangas.txt # default file for manga links to download
      #- ./crontab:/etc/cron.d/mangadlp # path to default crontab
      #- ./schedule:/app/schedules/daily # path to the default schedule which is run daily
    environment:
      - TZ=Europe/Zurich
      # - PUID= # custom userid - defaults to 4444
      # - PGID= # custom groupid - defaults to 4444


networks:
  appnet:
    name: mangadlp
    driver: bridge

