#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# set all env variables for further use. If variable is unset, it will have the defaults on the right side after ":="

# custom env vars
: "${MDLP_LANGUAGE:=en}"
: "${MDLP_FORCEVOL:=false}"
: "${MDLP_FILE_FORMAT:=cbz}"
: "${MDLP_DOWNLOAD_WAIT:=2}"
: "${MDLP_VERBOSE:=false}"
