#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# set all env variables for further use. If variable is unset, it will have the defaults on the right side after ":="


# custom env vars
#: "${var1:=/path1}"

