#######################
# build docker images #
#######################
# branch: master
# event: pull_request

depends_on:
  - tests

clone:
  git:
    when:
      branch: master
      event: pull_request
    image: woodpeckerci/plugin-git

pipeline:

  # build docker image for amd64 - x86
  dryrun-build-amd64:
    when:
      branch: master
      event: pull_request
    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      dry_run: true
      repo: olofvndrhr/manga-dlp
      platforms: linux/amd64
      dockerfile: docker/Dockerfile.amd64
      auto_tag: true
      auto_tag_suffix: linux-amd64
      build_args: BUILD_VERSION=${CI_COMMIT_TAG}

  # build docker image for arm64
  dryrun-build-arm64:
    when:
      branch: master
      event: pull_request
    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      dry_run: true
      repo: olofvndrhr/manga-dlp
      platforms: linux/arm64
      dockerfile: docker/Dockerfile.arm64
      auto_tag: true
      auto_tag_suffix: linux-arm64
      build_args: BUILD_VERSION=${CI_COMMIT_TAG}

