#######################
# build docker images #
#######################
# branch: master
# event: pull_request

depends_on:
  - tests

pipeline:

  # build docker image for amd64 - x86
  dryrun-build-amd64:
    when:
      branch: master
      event: pull_request
      platform: linux/amd64
    image: plugins/docker
    pull: if-not-exists
    settings:
      dry_run: true
      repo: olofvndrhr/manga-dlp
      context: docker
      dockerfile: docker/Dockerfile.amd64
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username:
        from_secret: cr-dhub-username
      password:
        from_secret: cr-dhub-key

  # build docker image for arm64
  dryrun-build-arm64:
    when:
      branch: master
      event: pull_request
      platform: linux/arm64
    image: plugins/docker
    pull: if-not-exists
    settings:
      dry_run: true
      repo: olofvndrhr/manga-dlp
      context: docker
      dockerfile: docker/Dockerfile.arm64
      auto_tag: true
      auto_tag_suffix: linux-arm64
      username:
        from_secret: cr-dhub-username
      password:
        from_secret: cr-dhub-key

