#############
# build app #
#############
# branch: master
# event: tag

depends_on:
  - tests

clone:
  git:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-git

pipeline:

  # build wheel and dist
  build-pypi:
    when:
      #branch: master
      event: tag
    image: cr.44net.ch/drone-plugins/test
    pull: true
    commands:
      - hatch build

  # release pypi
  release-pypi:
    when:
      #branch: master
      event: tag
    image: cr.44net.ch/drone-plugins/test
    pull: true
    secrets:
      - source: pypi_username
        target: HATCH_PYPI_USER
      - source: pypi_token
        target: HATCH_PYPI_AUTH
    commands:
      - hatch publish
