###################
# publish release #
###################
# branch: master
# event: tag

depends_on:
  - tests

clone:
  git:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-git

pipeline:

  # create release tar
  create-release-tar:
    when:
      #branch: master
      event: tag
    image: 'cr.44net.ch/baseimages/debian-base'
    pull: true
    commands:
      - tar -czf manga-dlp-${CI_COMMIT_TAG}.tar.gz --files-from=release-files.txt

  # create release-notes
  create-release-notes:
    when:
      #branch: master
      event: tag
    image: 'cr.44net.ch/baseimages/debian-base'
    pull: true
    commands:
      - bash 'release.sh' '--get-releasenotes' '${CI_COMMIT_TAG}'

  # publish release on gitea (git.44net.ch/olofvndrhr/manga-dlp)
  publish-release-gitea:
    when:
      #branch: master
      event: tag
    image: plugins/gitea-release
    pull: true
    settings:
      api_key:
        from_secret: gitea-olofvndrhr-token
      base_url: https://git.44net.ch
      files: manga-dlp-${CI_COMMIT_TAG}.tar.gz
      title: '${CI_COMMIT_TAG}'
      note: RELEASENOTES.md

  # publish release on github (github.com/olofvndrhr/manga-dlp)
  publish-release-github:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-github-release
    pull: true
    settings:
      api_key:
        from_secret: github-olofvndrhr-token
      files: manga-dlp-${CI_COMMIT_TAG}.tar.gz
      title: '${CI_COMMIT_TAG}'
      note: RELEASENOTES.md
