#########################################
# build and publish docker images arm64 #
#########################################
# branch: master
# event: tag

platform: linux/arm64

depends_on:
  - tests

clone:
  git:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-git

pipeline:

  # build and publish docker image for arm64
  build-arm64:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      repo: olofvndrhr/manga-dlp
      platforms: linux/arm64
      dockerfile: docker/Dockerfile.arm64
      auto_tag: true
      auto_tag_suffix: linux-arm64
      build_args: BUILD_VERSION=${CI_COMMIT_TAG}
      username:
        from_secret: cr-dhub-username
      password:
        from_secret: cr-dhub-key
