###################
# publish release #
###################
# branch: master
# event: tag

platform: linux/amd64

depends_on:
  - tests

clone:
  git:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-git

pipeline:

  # build wheel and dist
  build-pypi:
    when:
      #branch: master
      event: tag
    image: cr.44net.ch/ci-plugins/tests
    pull: true
    commands:
      - python3 -m hatch build

  # create release-notes
  create-release-notes:
    when:
      #branch: master
      event: tag
    image: cr.44net.ch/baseimages/debian-base
    pull: true
    commands:
      - bash get_release_notes.sh ${CI_COMMIT_TAG}

  # publish release on gitea (git.44net.ch/olofvndrhr/manga-dlp)
  publish-release-gitea:
    when:
      #branch: master
      event: tag
    image: plugins/gitea-release
    pull: true
    settings:
      api_key:
        from_secret: gitea-olofvndrhr-token
      base_url: https://git.44net.ch
      files: dist/*
      title: ${CI_COMMIT_TAG}
      note: RELEASENOTES.md

  # publish release on github (github.com/olofvndrhr/manga-dlp)
  publish-release-github:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-github-release
    pull: true
    settings:
      api_key:
        from_secret: github-olofvndrhr-token
      files: dist/*
      title: ${CI_COMMIT_TAG}
      note: RELEASENOTES.md

  # release pypi
  release-pypi:
    when:
      #branch: master
      event: tag
    image: cr.44net.ch/ci-plugins/tests
    pull: true
    secrets:
      - source: pypi_username
        target: HATCH_INDEX_USER
      - source: pypi_token
        target: HATCH_INDEX_AUTH
    commands:
      - python3 -m hatch publish
