###################
# publish pre-release #
###################
# branch: dev
# event: tag

platform: linux/amd64

depends_on:
  - tests

clone:
  git:
    image: woodpeckerci/plugin-git:v1.6.0
    when:
      event: tag
      tag: "*(-dev)"

pipeline:

  # build wheel and dist
  build-pypi:
    image: cr.44net.ch/ci-plugins/tests
    pull: true
    when:
      event: tag
      tag: "*(-dev)"
    commands:
      - python3 -m hatch build --clean

  # create pre-release-notes
  create-pre-release-notes:
    image: cr.44net.ch/baseimages/debian-base
    pull: true
    when:
      event: tag
      tag: "*(-dev)"
    commands:
      - bash get_release_notes.sh ${CI_COMMIT_TAG%%-dev}

  # publish pre-release on github (github.com/olofvndrhr/manga-dlp)
  publish-pre-release-github:
    image: woodpeckerci/plugin-github-release
    pull: true
    when:
      event: tag
      tag: "*(-dev)"
    settings:
      api_key:
        from_secret: github-olofvndrhr-token
      files: dist/*
      title: ${CI_COMMIT_TAG}
      note: RELEASENOTES.md
      prerelease: true

  # publish pre-release on gitea (git.44net.ch/olofvndrhr/manga-dlp)
  publish-pre-release-gitea:
    image: woodpeckerci/plugin-gitea-release
    pull: true
    when:
      event: tag
      tag: "*(-dev)"
    settings:
      api_key:
        from_secret: gitea-olofvndrhr-token
      base_url: https://git.44net.ch
      files: dist/*
      title: ${CI_COMMIT_TAG}
      note: RELEASENOTES.md
      prerelease: true

#  # pre-release pypi
#  pre-release-pypi:
#    image: cr.44net.ch/ci-plugins/tests
#    pull: true
#    when:
#      event: tag
#      tag: "*(-dev)"
#    secrets:
#      - source: pypi_username
#        target: HATCH_INDEX_USER
#      - source: pypi_token
#        target: HATCH_INDEX_AUTH
#    commands:
#      - python3 -m hatch publish --no-prompt --yes
