###########################
# publish docker manifest #
###########################
# branch: master
# event: tag

platform: linux/amd64

depends_on:
  - publish_docker_amd64
  - publish_docker_arm64

clone:
  git:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-git

pipeline:

  # publish docker manifest for automatic multi arch pulls
  publish-manifest:
    when:
      #branch: master
      event: tag
    image: plugins/manifest
    pull: true
    settings:
      spec: docker/manifest.tmpl
      auto_tag: true
      ignore_missing: true
      username:
        from_secret: cr-dhub-username
      password:
        from_secret: cr-dhub-key
