#########################################
# build and publish docker images amd64 #
#########################################
# branch: master
# event: tag

platform: linux/amd64

depends_on:
  - tests

clone:
  git:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-git

pipeline:

  # build and publish docker image for amd64 - x86
  build-amd64:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      repo: olofvndrhr/manga-dlp
      platforms: linux/amd64
      dockerfile: docker/Dockerfile.amd64
      auto_tag: true
      auto_tag_suffix: linux-amd64
      build_args: BUILD_VERSION=${CI_COMMIT_TAG}
      username:
        from_secret: cr-dhub-username
      password:
        from_secret: cr-dhub-key
