##################################
# test build docker images amd64 #
##################################
# branch: master
# event: pull_request

platform: linux/amd64

depends_on:
  - tests

clone:
  git:
    image: woodpeckerci/plugin-git:v1.6.0
    when:
      branch: master
      event: pull_request

pipeline:

  # build docker image for amd64 - x86
  test-build-amd64:
    image: plugins/docker
    pull: true
    when:
      branch: master
      event: pull_request
    settings:
      dry_run: true
      repo: olofvndrhr/manga-dlp
      platforms: linux/amd64
      dockerfile: docker/Dockerfile.amd64
      auto_tag: true
      auto_tag_suffix: linux-amd64-test
      build_args: BUILD_VERSION=test
