##############################
# code testing and analysis #
#############################
# branch: all
# event: all

clone:
  git:
    image: woodpeckerci/plugin-git

pipeline:

  # check code style - shell
  test-shfmt:
    image: cr.44net.ch/ci-plugins/tests
    pull: true
    commands:
      - shfmt -d -i 4 -bn -ci -sr .

  # check code style - python
  test-black:
    image: cr.44net.ch/ci-plugins/tests
    pull: true
    commands:
      - python3 -m black --check --diff .

  # check imports - python
  test-isort:
    image: cr.44net.ch/ci-plugins/tests
    pull: true
    commands:
      - python3 -m isort --check-only --diff .

  # check unused and missing imports
  test-autoflake:
    image: cr.44net.ch/ci-plugins/tests
    pull: true
    commands:
      - python3 -m autoflake --remove-all-unused-imports -r -v mangadlp/
      - python3 -m autoflake --check --remove-all-unused-imports -r -v mangadlp/

  # check static typing - python
  test-mypy:
    image: cr.44net.ch/ci-plugins/tests
    pull: true
    commands:
      - python3 -m mypy --install-types --non-interactive mangadlp/

  # multiple linters with pylama
  test-pylama:
    image: cr.44net.ch/ci-plugins/tests
    pull: true
    commands:
      - python3 -m pylama mangadlp/

  # test code with different python versions
  test-tox-pytest:
    when:
      event: [ push ]
    image: cr.44net.ch/ci-plugins/tests
    pull: true
    commands:
      - python3 -m tox -e basic

  # generate coverage report
  test-tox-coverage:
    when:
      branch: master
      event: [ pull_request ]
    image: cr.44net.ch/ci-plugins/tests
    pull: true
    commands:
      - python3 -m tox -e coverage

  # analyse code with sonarqube and upload it
  sonarqube-analysis:
    when:
      branch: master
      event: [ pull_request ]
    image: cr.44net.ch/ci-plugins/sonar-scanner
    pull: true
    settings:
      sonar_host: https://sonarqube.44net.ch
      sonar_token:
        from_secret: sq-44net-token
      usingProperties: true
