##################
# test tox amd64 #
##################
# branch: master
# event: pull_request

platform: linux/amd64

depends_on:
  - tests

clone:
  git:
    image: woodpeckerci/plugin-git:v1.6.0
    when:
      branch: master
      event: pull_request

pipeline:

  # test code with different python versions - amd64
  test-tox-amd64:
    image: cr.44net.ch/ci-plugins/multipy
    pull: true
    when:
      branch: master
      event: pull_request
    commands:
      - just test_tox
