##################
# test build app #
##################
# branch: master
# event: pull_request

depends_on:
  - tests

clone:
  git:
    when:
      branch: master
      event: pull_request
    image: woodpeckerci/plugin-git

pipeline:

  # build wheel and dist
  test-build-pypi:
    when:
      branch: master
      event: pull_request
    image: cr.44net.ch/drone-plugins/test
    pull: true
    commands:
      - hatch build

#  # test code with different python versions - amd64
#  test-tox-amd64:
#    when:
#      branch: master
#      event: pull_request
#    image: cr.44net.ch/drone-plugins/test:1-linux-amd64
#    pull: true
#    commands:
#      - tox
#
#  # test code with different python versions - arm64
#  test-tox-arm64:
#    when:
#      branch: master
#      event: pull_request
#    image: cr.44net.ch/drone-plugins/test:1-linux-arm64
#    pull: true
#    commands:
#      - tox
