################
# test release #
################
# branch: master
# event: pull_request

platform: linux/amd64

depends_on:
  - tests

clone:
  git:
    when:
      branch: master
      event: pull_request
    image: woodpeckerci/plugin-git

pipeline:

  # build wheel and dist
  test-build-pypi:
    when:
      branch: master
      event: pull_request
    image: cr.44net.ch/ci-plugins/tests
    pull: true
    commands:
      - python3 -m hatch build --clean

  # create release-notes
  test-create-release-notes:
    when:
      branch: master
      event: pull_request
    image: cr.44net.ch/baseimages/debian-base
    pull: true
    commands:
      - bash get_release_notes.sh latest
      - cat RELEASENOTES.md
